# Generated by Django 4.2.2 on 2023-06-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compromisso', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
