# Generated by Django 4.2.2 on 2023-06-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='date',
        ),
        migrations.AddField(
            model_name='agenda',
            name='date_fim',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='date_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
