# Generated by Django 4.2.2 on 2023-06-20 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_agenda_date_agenda_date_fim_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agenda',
            new_name='Compromisso',
        ),
    ]
