# Generated by Django 4.2.2 on 2023-06-23 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_convidado_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convidado',
            old_name='user',
            new_name='user_id',
        ),
    ]
