# Generated by Django 4.2.2 on 2023-06-23 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_rename_user_convidado_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convidado',
            old_name='user_id',
            new_name='user',
        ),
    ]
